name: Build

on:
  workflow_call:
    inputs:
      docker_context_path:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      java_version:
        type: string
        default: '11'

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'
          cache: maven
      - name: Retrieve project version
        id: get_version
        run: |
          echo "::set-output name=project_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout  --file pom.xml)"
      - name: Maven compile
        run: mvn -B compile --file pom.xml
      - name: Maven integration test
        run: mvn -B integration-test --file pom.xml
      - name: Maven unit test
        run: mvn -B test --file pom.xml
      - name: Maven install
        run: mvn -B install -Pdocker -DskipTests=true --file pom.xml
      - name: Docker build
        run: |
          docker build -f ${{ inputs.dockerfile_path }}/Dockerfile ${{ inputs.docker_context_path }} -t ${{ github.event.repository.name }}:${{ steps.get_version.outputs.project_version }}"
      - name:
        run: |
          wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O ./.github/html.tpl
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ github.event.repository.name }}:${{ steps.get_version.outputs.project_version }}'
          format: 'template'
          template: '@.github/html.tpl'
          exit-code: '1'
          ignore-unfixed: true
          output: "trivy_report.html"
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: Dependency check report
          path: ${{github.workspace}}/trivy_report.html
